### ISSUE TITLE
Feasibillity study_feedback_Dimitra

### ISSUE THREAD

**Issue by DimitraM** [DimitraM/Room_Design#14]
Στο project description έχω γράψει και σχεδιάσει ότι η εφαρμογή παίρνει δεδομένα από άλλους χρήστες και έτσι κάνει προτάσεις. Εδώ, αντίθετα έχουμε γράψει ότι η εφαρμογή θα δίνει tips σύμφωνα με κανόνες εσωτερικής διακόσμισης. Πως ακριβώς το έχεις σκεφτεί εσύ; Ο λόγος που το έγραψα ότι θα το υλοποιήσουμε με δεδομένα από άλλους χρήστες είναι επειδή σκέφτηκα έναν τρόπο να υλοποιείται με εκπαίδευση νευρονικού. Αν έχεις άλλη ιδέα γράψε εδώ να το διορθώσω και στο project description
@Andreas-Ts

**Comment by Andreas-Ts** [comment]
Εγώ όταν είχα γράψει το feasibility, το είχα σκεφτεί ότι θα βάλουμε
χειροκίνητα κανόνες που θα κρίνουν που θα μπουν τα αντικείμενα στο χώρου.
Δεν είναι αντικρουόμενα, θα μπορουσαν να μπουν και τα δυο,οτι θες. Θα το
αλλάξω αν είναι για να γίνεται και με νευρονικα, ίσως μπορουμε να πουμε οτι
θα προσλαβουμε ένα άτομο με εμπειρία στα νευρωνικα.

Στις Κυρ, 12 Μαρ 2023, 9:54 μ.μ. ο χρήστης DimitraM <
***@***.***> έγραψε:

**Comment by DimitraM** [comment]
Δεν χρειάζεται να προσλάβουμε κάποιο. Θα το κάνουμε με ανάλυση δεδομένων και AI
