### ISSUE TITLE
Team-plan-v0.1

### ISSUE THREAD

**Issue by DimitraM** [DimitraM/Room_Design#2]

**Comment by TrueThanos** [comment]
![pert_chart(team plan)](https://user-images.githubusercontent.com/121426063/222953346-6a55df39-ccef-44e4-804f-3d489c1c141c.png)
![table-pert_chart(team plan)](https://user-images.githubusercontent.com/121426063/222953349-f96f010b-bd96-41ab-9266-3ab37fac1df0.png)

**Comment by TrueThanos** [comment]
![table-pert_chart(team plan)](https://user-images.githubusercontent.com/121426063/222953427-874ce38c-b01b-41ed-9fd9-3006a42069d2.png)
![pert_chart(team plan)](https://user-images.githubusercontent.com/121426063/222953428-76596d54-80f4-4b85-9c05-216741cb64bd.png)

**Comment by DimitraM** [comment]
@TrueThanos Δες την αναφορά που μορφοποίησα και αν θέλεις πρόσθεσε κάτι έξτρα. Η τελική μορφή που έφτιαξα είναι στο  main branch
